version: "3.8"
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
  ps:
    build:
      context: ./parrot-world-server
      dockerfile: ../Dockerfile.ps
    environment:
      - NODE_ENV=development
      - CORS_ORIGIN=http://localhost:40212
      - PORT=31203
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=parrot_world
      - DB_PORT=3306
      - JWT_SECRET=thisistesttokenforjwtauthoritythisistesttokenforjwtauthoritythisistesttokenforjwtauthority
      - SALT=10
      - MAIL_HOST=TEST_MAIL_HOST
      - MAIL_PASSWORD=TEST_MAIL_PASSWORD
    ports:
      - "31203:31203"
    restart: always
    volumes:
      - ./parrot-world-server/src/:/parrot-world-server/src/
      - ./parrot-world-server/test/:/parrot-world-server/test/
    depends_on:
      - db
  pc:
    build:
      context: ./parrot-world-client
      dockerfile: ../Dockerfile.pc
    environment:
      - NODE_ENV=development
      - API_ENDPOINT=http://localhost:31203
    ports:
      - "40212:40212"
    depends_on:
      - ps
    restart: always
    volumes:
      - ./parrot-world-client/src/:/parrot-world-client/src/